[package]
name = "vamc_parser"
version = "0.1.0"
authors = ["Fausto Núñez Alberro <fausto.nunez@mailbox.org>"]
edition = "2018"

[lib]
name = "vamc_parser"
path = "src/lib.rs"

[dependencies]
vamc_errors = { path = "../libvamc_errors" }
vamc_lexer = { path = "../libvamc_lexer" }
