# Includes only settings that differ from defaults. Defaults here: https://rust-lang.github.io/rustfmt
blank_lines_lower_bound = 0
brace_style = "PreferSameLine"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
match_block_trailing_comma = true
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true
