[package]
name = "vamc_lexer"
version = "0.1.0"
authors = ["Fausto Núñez Alberro <fausto.nunez@mailbox.org>"]
edition = "2021"

[lib]
name = "vamc_lexer"
path = "src/lib.rs"

[dependencies]
unicode-xid = "0.2.1"
